# frozen_string_literal: true

control 'captcha generation' do
  impact 0.5
  title 'should be working'

  # example captcha command generated by simple_captcha2 gem
  captcha_cmd = 'convert -fill darkgreen -background white -size 120x20 -wave 1x96 '\
    '-gravity Center -pointsize 22 -implode 0.2 label:01234 jpeg:-'

  describe command(captcha_cmd) do
    its('stderr') { should eq '' }
    its('exit_status') { should eq 0 }
  end
end
